CREATE SCHEMA IF NOT EXISTS quiz;
CREATE SCHEMA IF NOT EXISTS mood;
CREATE SCHEMA IF NOT EXISTS activity;
CREATE SCHEMA IF NOT EXISTS thought;
CREATE SCHEMA IF NOT EXISTS habit;
CREATE SCHEMA IF NOT EXISTS gratitude;